# Generated by Django 4.2.27 on 2026-02-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="Shekhar's Portfolio", max_length=255)),
                ('meta_title', models.CharField(default='Shekhar Dhakal | Backend & RPA Architect', max_length=255)),
                ('meta_description', models.TextField(default='Portfolio of Shekhar Dhakal, a Backend Engineer specialized in high-performance Python ecosystems and Robotic Process Automation (RPA).')),
                ('meta_keywords', models.CharField(default='backend, rpa, python, django, devops', max_length=500)),
                ('about_section_title', models.CharField(default='01. Background', max_length=100)),
                ('skills_section_title', models.CharField(default='02. Expertise', max_length=100)),
                ('experience_section_title', models.CharField(default='03. Career Path', max_length=100)),
                ('portfolio_section_title', models.CharField(default='04. Selected Projects', max_length=100)),
                ('contact_section_title', models.CharField(default='05. Contact', max_length=100)),
                ('email', models.EmailField(default='shekhardhakal2015@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+977 9840177381', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('facebook_link', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
