# Generated by Django 4.2.28 on 2026-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='experience',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Use primary color for timeline dot'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_bullet_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_bullet_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_bullet_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_company',
            field=models.CharField(blank=True, help_text='e.g. MetaCloud Solution Pvt Ltd', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_role_location',
            field=models.CharField(blank=True, help_text='e.g. Software Engineer (Lalitpur, Nepal)', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='accent_color',
            field=models.CharField(blank=True, help_text='e.g. primary, secondary, accent', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_name',
            field=models.CharField(blank=True, help_text='Lucide icon name, e.g. layers, trending-up', max_length=50),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='location',
            field=models.CharField(blank=True, help_text='Short location display e.g. Kathmandu, Nepal', max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='FontAwesome or Lucide icon name', max_length=50),
        ),
    ]
