# Generated by Django 5.2.1 on 2026-04-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certification_education_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order'], 'verbose_name': 'Certification', 'verbose_name_plural': 'Certifications'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configuration'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='project',
            name='accent_color',
            field=models.CharField(blank=True, help_text='e.g. primary, secondary, accent, blue-400', max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Font Awesome class (e.g. fa-brands fa-python, fa-solid fa-robot). Leave blank to use default icon by skill name.', max_length=50),
        ),
    ]
